### ISSUE TITLE
Unable to Access Extra payload

### ISSUE THREAD

**Issue by ghensto** [flutter-webrtc/callkeep#102]
https://github.com/flutter-webrtc/callkeep/blob/5bb638521ea078eba243a1bf190f5e25d3056284/ios/Classes/CallKeep.m#L258

Currently the extra payload that should allow us to add non Callkit related data is being ignored.

**Comment by ghensto** [comment]
#83

**Comment by simone-folador** [comment]
Hi @ghensto, how could we use the extra payload in our application? We see the payload in the Logs but it's not passed to Flutter. Is this something you are going to change and add in the near future?

**Comment by ghensto** [comment]
> Hi @ghensto, how could we use the extra payload in our application? We see the payload in the Logs but it's not passed to Flutter. Is this something you are going to change and add in the near future?

You will need to for the repo and make the following changes:
![image](https://user-images.githubusercontent.com/10698485/153834911-b0139b73-861b-4396-8440-8bce70ff56a3.png)

**Comment by simone-folador** [comment]
Hi @ghensto , thank you. 
We did know how to implement the requested changes but we just wanted to use your library. 
Can we do a pull request and insert the changes you proposed in the previous message? 

Thank you very much

**Comment by ghensto** [comment]
> Hi @ghensto , thank you. 
> 
> We did know how to implement the requested changes but we just wanted to use your library. 
> 
> Can we do a pull request and insert the changes you proposed in the previous message? 
> 
> 
> 
> Thank you very much

Sorry, I'm not the admin of this repo. Contact @cloudwebrtc
