### ISSUE TITLE
type 'Null' is not a subtype of type 'List<String>' in type cast

### ISSUE THREAD

**Issue by Rizardomon** [flutter-webrtc/callkeep#132]
I am trying to get the user permissions through the callkeep.setup() function, but it gives me this error when trying to execute the function.
I call the required permissions first and make sure they are accepted, but it still gives me the error.
I am using flutter 2.2.0 with null safety.

![image](https://user-images.githubusercontent.com/57680110/148814415-f223e2ad-c8a4-40f1-a5d9-7d5741a95b36.png)

![image](https://user-images.githubusercontent.com/57680110/148814749-c3002eca-fa6f-4e2e-abb2-fcc63c787e36.png)

**Comment by yg271828** [comment]
workaround, that works for me:
add
```
'additionalPermissions': ['']
```
in 'android' section

**Comment by Rizardomon** [comment]
> workaround, that works for me: add
> 
> ```
> 'additionalPermissions': ['']
> ```
> 
> in 'android' section

Where in the android section? On manifest of my project?

**Comment by yg271828** [comment]
android section in your calkeep setup:
```dart
final _callSetup = <String, dynamic>{
    'ios': {
      'appName': 'My app',
    },
    'android': {
      'alertTitle': 'Permissions required',
      'alertDescription':
          'This application needs to access your phone accounts',
      'cancelButton': 'Cancel',
      'okButton': 'ok',
      // Required to get audio in background when using Android 11
      'foregroundService': {
        'channelId': com.company.my',
        'channelName': 'Foreground service for my app',
        'notificationTitle': 'My app is running on background',
        'notificationIcon': 'mipmap/ic_notification_launcher',
      },
      'additionalPermissions': [
        'android.permission.READ_PHONE_STATE',
        'android.permission.CALL_PHONE',
        'android.permission.RECORD_AUDIO',
      ],
    },
  };
```

**Comment by Rizardomon** [comment]
Thanks man, i tried here and works just fine!!
