### ISSUE TITLE
How to customize answering incoming call ?

### ISSUE THREAD

**Issue by MaheshPeri19** [flutter-webrtc/callkeep#14]
Hi,

I have two questions.

1) How to remove dialing pad screen after click on answer button ? Because i want to open the app with new screen.
2) How to open the app when click on answer button if app is in background mode ?

I am using custom calling, but phone number based call. Whenever receiver gets the call, i am using this package to notify the user for incoming call. When user clicks on answer button, i want to open the app (if it is in background) and show some screen. So i dont want keypad screen.

Please help me on this.

**Comment by ghenry** [comment]
You need to use the self managed version. https://developer.android.com/guide/topics/connectivity/telecom/selfManaged

I'm not sure if we can with this yet @cloudwebrtc   ?

**Comment by MaheshPeri19** [comment]
Okay. Thank you. I will check that.

**Comment by jabguru** [comment]
Please what did you do? Did you find a solution?

**Comment by MaheshPeri19** [comment]
@jabguru 

No. I did not find any solution for this. We kept aside calling and ringtone functionality and done like a zoom video call using url.

**Comment by ghenry** [comment]
You can't. It shows the native screen if you ask it to.

What you can do is show your own notification with action buttons on
Android and then inform/query the connection service of this call.

See the awesome notifications plugin for the action buttons.

**Comment by jabguru** [comment]
> You can't. It shows the native screen if you ask it to. What you can do is show your own notification with action buttons on Android and then inform/query the connection service of this call. See the awesome notifications plugin for the action buttons.

Thanks alot, it's an awesome plugin
