### ISSUE TITLE
Complete working example with Agora RTC Engine

### ISSUE THREAD

**Issue by AppicSoftwares** [flutter-webrtc/callkeep#146]
Hello 
Please share a complete working example for integrate Callkeep with  Agora RTC engine for background and kill state audio video calling in flutter

**Comment by cloudwebrtc** [comment]
If you can contact Agora for sponsorship, it might be possible, otherwise, we have no reason to support a commercial company with open source technology around their SDK.

**Comment by HasanAlyazidi** [comment]
@AppicSoftwares Have you found a good package that is compatible with Agora?
