### ISSUE TITLE
Your app uses a bad version of WebRTC, which contains security vulnerabilities.

### ISSUE THREAD

**Issue by rvharjinderbains** [flutter-webrtc/callkeep#155]
I have integrated callkeep plugin in my project and published app on google play store. I got below mentioned error message from google :- 

"Your app uses a bad version of WebRTC, which contains security vulnerabilities."

I am using :-
Flutter : 2.10.5
Dart: 2.16.2 
callkeep :0.3.2

Please provide me the solution

Thank you

**Comment by cloudwebrtc** [comment]
So what version of webrtc are you using? AFAIK callkeep doesn't include webrtc sdk

**Comment by rvharjinderbains** [comment]
@cloudwebrtc I am not using webrtc directly, I have added plugin callkeep :0.3.2.

**Comment by rvharjinderbains** [comment]
@cloudwebrtc Thank you very much for your response. I got it in jitsi library .
