### ISSUE TITLE
Different behaviours on iOS and Android

### ISSUE THREAD

**Issue by postacik** [flutter-webrtc/callkeep#18]
Hi,
I'm experimenting with the example code on iOS and Android.

On iOS (v12), when I click the "Accept" button, the OS calling screen closes and example app is displayed.

But on Android 9, when I click the "Accept" button, the calling screen stays intact and I can not switch to my app but for a video call switching to the main app is mandatory.

Is this the expected behaviour?

**Comment by aravindhkumar23** [comment]
@postacik Did you found the solution , I'm also facing this. can you guide me to take control to application instead of staying in calling screen.

**Comment by postacik** [comment]
Unfortunately this is the default behaviour. You can test it with WhatsApp on Android and iOS and see how they've handled it.
