### ISSUE TITLE
Permissions cause this? Missing channel FlutterCallkeep.Method

### ISSUE THREAD

**Issue by ghenry** [flutter-webrtc/callkeep#2]
I've not checked perms as I was just playing, but would that cause this in my background message?:

```
I/flutter ( 7734): Background Full Message: {data: {callerId: 01224900123}}
I/flutter ( 7734): Background Message: {data: {callerId: 01224900123}}
I/flutter ( 7734): Display incoming call now
E/flutter ( 7734): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method hasPhoneAccount on channel FlutterCallKeep.Method)
E/flutter ( 7734): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:159:7)
E/flutter ( 7734): <asynchronous suspension>
E/flutter ( 7734): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
```

**Comment by ghenry** [comment]
Seems to just be how background messages are handled. Same for local notifications:
```
lutter (25882): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: MissingPluginException(No implementation found for method show on channel dexterous.com/flutter/local_notifications)```

**Comment by ghenry** [comment]
Need to do on Android side as per:

    https://stackoverflow.com/questions/61067558/flutter-cant-use-any-plugin-in-onbackgroundmessage

**Comment by MaheshPeri19** [comment]
How give permission by default ?

I am calling displayincomingCall Method in FCM onMessage and OnBackgroundMessage methods. When i click on first time time it is showing "Application needs to access to phone accounts".

Without asking this persmission, by default how to enable it ?

and also how to bring app from background to foreground ?
I have used this package, but not working ==> bringtoforeground: ^0.0.2

Please help on this.
