### ISSUE TITLE
JSON details and extra fields

### ISSUE THREAD

**Issue by ghenry** [flutter-webrtc/callkeep#27]
In the JSON payload, what do we do with badge?

Can we change `number` to `caller_id` or `from_number` and an extra field called `to_number` so we know what number they caller called?

```
{
   "aps":{
      "alert":{
         "callkeep":{
            "title":"Incoming call",
            "number":"01224900123"
         },
         "badge":{
            "badge":"0"
         }
      }
   }
}
```

**Comment by cloudwebrtc** [comment]
Sorry, I forgot to describe the payload format, I just added the 'callkeep' object at the root of the json.

```
{
	"callkeep": {
		"title": "Incoming Call",
		"number": "+8618627935526"
	},
	"badge": {
		"badge": "0"
	}
}
```

**Comment by ghenry** [comment]
Yeah, I saw that in the code, but can't see title or badge being used?

**Comment by ghenry** [comment]
I'll add I'm getting the token correctly.

**Comment by cloudwebrtc** [comment]
I'm not sure those are required, so we can discuss and determine which fields must exist.
