### ISSUE TITLE
Integration with sip-ua

### ISSUE THREAD

**Issue by ghenry** [flutter-webrtc/callkeep#5]
Hi @cloudwebrtc 

What are the recommended callbacks to set as per the example app if using sip-ua to manage the call?

I've now got `displayIncomingCall` triggering on a push from FCM in `onBackgroundMessage`. 

Thanks.

**Comment by ghenry** [comment]
I mean, can you attached sip-ua/webrtc and keep the native dialler screen?

**Comment by cloudwebrtc** [comment]
So far, I only ported the plugin. It seems that I need a test environment that can wake up the app from APNS or FCM and perform RFC8599 testing.

**Comment by ghenry** [comment]
As soon as we get the contact headers sorted on dart sip UA in
https://github.com/cloudwebrtc/dart-sip-ua/issues/89 I can test.

I'll be working on that this week then I just need
https://github.com/cloudwebrtc/dart-sip-ua/issues/105 and I can go live on
app stores.

**Comment by ghenry** [comment]
Hi @cloudwebrtc 

So I have a working RFC8599 env. I just need to understand how to hook an Accept / Deny key press to `_handleAccept`

and put this into Android for handling handling a call: https://github.com/doneservices/flutter_callkeep/wiki/Native-android-code-that-handles-incoming-calls as I want to do self managed:

https://developer.android.com/guide/topics/connectivity/telecom/selfManaged

So push comes in, we call CallKeep and then present our own local notification with Actions using above example from the other call keep github repo.

My background pushes are working nicely on Android. Outbound calls are no problem.

Thanks.

**Comment by ghenry** [comment]
So https://github.com/flutter-webrtc/dart-sip-ua/issues/89 is done.

**Comment by cloudwebrtc** [comment]
Cool, nice work.

**Comment by ghenry** [comment]
> Cool, nice work.

For our use anyway. I wouldn't say dart-sip-ua is a 100% RFC8599 compliant User Agent, but it works well against OpenSIPS 3.1 with RFC8599 on that side. Very close and the compliance is in your own hands.

Thanks.

**Comment by ghenry** [comment]
Got quote far with this now, but I think callkeep does its own audio and BT?

```
https://github.com/flutter-webrtc/callkeep/blob/0502639460b8398255727367f030ef8f0e1b2156/android/src/main/java/io/wazo/callkeep/VoiceConnection.java#L73

I/TelecomFramework( 7878): VoiceConnectionService: onAudioStateChanged TC@7_1 [AudioState isMuted: false, route: SPEAKER, supportedRouteMask: SPEAKER, activeBluetoothDevice: [null], supportedBluetoothDevices: []]: (NCSSF.aC->ICFG.sF->ICFG.sF->ICFG.sF->CARSM.pM_UPDATE_SYSTEM_AUDIO_ROUTE)->CS.cASC->H.CS.cASC(cast)@E-CFs
I/TelecomFramework( 7878): VoiceConnectionService: onAudioStateChanged TC@7_1 [AudioState isMuted: false, route: SPEAKER, supportedRouteMask: SPEAKER, activeBluetoothDevice: [null], supportedBluetoothDevices: []]: (NCSSF.aC->ICFG.sF->ICFG.sF->ICFG.sF->CAMSM.pM_2002->CARSM.pM_SWITCH_FOCUS)->CS.cASC->H.CS.cASC(cast)@E-CFs
I/TelecomFramework( 7878): VoiceConnectionService: answer TC@7_1: (ICA.aC->CSFM.rF)->CS.an->H.CS.an(cgad/cast)@E-CIM
D/RNCK:VoiceConnection( 7878): onAnswer called
D/RNCK:VoiceConnection( 7878): onAnswer executed

...


D/RTCAudioManager( 7878): --- updateAudioDeviceState: wired headset=false, BT state=HEADSET_UNAVAILABLE
D/RTCAudioManager( 7878): Device status: available=[], selected=NONE, user selected=NONE
D/RTCAudioManager( 7878): setAudioDeviceInternal(device=SPEAKER_PHONE)
D/RTCAudioManager( 7878): New device status: available=[SPEAKER_PHONE, EARPIECE], selected=SPEAKER_PHONE
D/FlutterWebRTCPlugin( 7878): onAudioManagerDevicesChanged: [SPEAKER_PHONE, EARPIECE], selected: SPEAKER_PHONE
D/RTCAudioManager( 7878): --- updateAudioDeviceState done
D/RTCAudioManager( 7878): AudioManager started
I/flutter ( 7878): [2020-10-05 16:05:15.447] Level.debug rtc_session.dart:1572 ::: emit "peerconnection"
I/FlutterWebRTCPlugin( 7878): getUserMedia(audio): mandatory: [], optional: [googNoiseSuppression: true, googEchoCancellation: true, echoCancellation: true, googEchoCancellation2: true, googDAEchoCancellation: true]
D/FlutterWebRTCPlugin( 7878): MediaStream id: 25425f5d-e23b-4c88-8f06-f9213d7ce135
D/FlutterWebRTCPlugin( 7878): addStreamcom.cloudwebrtc.webrtc.utils.AnyThreadResult@7872a1a
I/flutter ( 7878): [2020-10-05 16:05:15.465] Level.debug rtc_session.dart:625 ::: emit "sdp"
D/FlutterWebRTCPlugin( 7878): peerConnectionSetRemoteDescription() start
D/FlutterWebRTCPlugin( 7878): onAddTrack
D/FlutterWebRTCPlugin( 7878): peerConnectionSetRemoteDescription() end

```

so I do this:

```
class CallController extends GetxController implements SipUaHelperListener {
  final logger = Logger(printer: PrettyPrinter(printTime: true));
  final _helper = Get.find<SipHelperService>().helper;
  Call _call;
  CallState _callState;

  Call get call => this._call;
  CallState get callState => this._callState;
  SIPUAHelper get helper => this._helper;
  FlutterCallkeep get callKeep => this._callKeep;

...

  @override
  void callStateChanged(Call call, CallState callState) {
    logger.d(callState.state);
    // TODO Check outbound calls from DialpadScreen()
    //if (callState.state == CallStateEnum.CALL_INITIATION) {
    this._call = call;
    this._callState = callState;
    //}
  }

...

  void _callKeepCallBacks() {
    _callKeep.on(CallKeepPerformAnswerCallAction(), answerCall);
    _callKeep.on(CallKeepDidPerformDTMFAction(), didPerformDTMFAction);
    _callKeep.on(
        CallKeepDidReceiveStartCallAction(), didReceiveStartCallAction);
    _callKeep.on(CallKeepDidToggleHoldAction(), didToggleHoldCallAction);
    _callKeep.on(
        CallKeepDidPerformSetMutedCallAction(), didPerformSetMutedCallAction);
    _callKeep.on(CallKeepPerformEndCallAction(), endCall);
  }

  Future<void> answerCall(CallKeepPerformAnswerCallAction event) async {
    final String callUUID = event.callUUID;
    logger.d('[answerCall] $callUUID');
    _callKeep.setCurrentCallActive(callUUID);
    call.answer(helper.buildCallOptions());
  }
```

**Comment by C4sse** [comment]
> Got quote far with this now, but I think callkeep does its own audio and BT?
> 
> ```
> https://github.com/flutter-webrtc/callkeep/blob/0502639460b8398255727367f030ef8f0e1b2156/android/src/main/java/io/wazo/callkeep/VoiceConnection.java#L73
> 
> I/TelecomFramework( 7878): VoiceConnectionService: onAudioStateChanged TC@7_1 [AudioState isMuted: false, route: SPEAKER, supportedRouteMask: SPEAKER, activeBluetoothDevice: [null], supportedBluetoothDevices: []]: (NCSSF.aC->ICFG.sF->ICFG.sF->ICFG.sF->CARSM.pM_UPDATE_SYSTEM_AUDIO_ROUTE)->CS.cASC->H.CS.cASC(cast)@E-CFs
> I/TelecomFramework( 7878): VoiceConnectionService: onAudioStateChanged TC@7_1 [AudioState isMuted: false, route: SPEAKER, supportedRouteMask: SPEAKER, activeBluetoothDevice: [null], supportedBluetoothDevices: []]: (NCSSF.aC->ICFG.sF->ICFG.sF->ICFG.sF->CAMSM.pM_2002->CARSM.pM_SWITCH_FOCUS)->CS.cASC->H.CS.cASC(cast)@E-CFs
> I/TelecomFramework( 7878): VoiceConnectionService: answer TC@7_1: (ICA.aC->CSFM.rF)->CS.an->H.CS.an(cgad/cast)@E-CIM
> D/RNCK:VoiceConnection( 7878): onAnswer called
> D/RNCK:VoiceConnection( 7878): onAnswer executed
> 
> ...
> 
> 
> D/RTCAudioManager( 7878): --- updateAudioDeviceState: wired headset=false, BT state=HEADSET_UNAVAILABLE
> D/RTCAudioManager( 7878): Device status: available=[], selected=NONE, user selected=NONE
> D/RTCAudioManager( 7878): setAudioDeviceInternal(device=SPEAKER_PHONE)
> D/RTCAudioManager( 7878): New device status: available=[SPEAKER_PHONE, EARPIECE], selected=SPEAKER_PHONE
> D/FlutterWebRTCPlugin( 7878): onAudioManagerDevicesChanged: [SPEAKER_PHONE, EARPIECE], selected: SPEAKER_PHONE
> D/RTCAudioManager( 7878): --- updateAudioDeviceState done
> D/RTCAudioManager( 7878): AudioManager started
> I/flutter ( 7878): [2020-10-05 16:05:15.447] Level.debug rtc_session.dart:1572 ::: emit "peerconnection"
> I/FlutterWebRTCPlugin( 7878): getUserMedia(audio): mandatory: [], optional: [googNoiseSuppression: true, googEchoCancellation: true, echoCancellation: true, googEchoCancellation2: true, googDAEchoCancellation: true]
> D/FlutterWebRTCPlugin( 7878): MediaStream id: 25425f5d-e23b-4c88-8f06-f9213d7ce135
> D/FlutterWebRTCPlugin( 7878): addStreamcom.cloudwebrtc.webrtc.utils.AnyThreadResult@7872a1a
> I/flutter ( 7878): [2020-10-05 16:05:15.465] Level.debug rtc_session.dart:625 ::: emit "sdp"
> D/FlutterWebRTCPlugin( 7878): peerConnectionSetRemoteDescription() start
> D/FlutterWebRTCPlugin( 7878): onAddTrack
> D/FlutterWebRTCPlugin( 7878): peerConnectionSetRemoteDescription() end
> ```
> 
> so I do this:
> 
> ```
> class CallController extends GetxController implements SipUaHelperListener {
>   final logger = Logger(printer: PrettyPrinter(printTime: true));
>   final _helper = Get.find<SipHelperService>().helper;
>   Call _call;
>   CallState _callState;
> 
>   Call get call => this._call;
>   CallState get callState => this._callState;
>   SIPUAHelper get helper => this._helper;
>   FlutterCallkeep get callKeep => this._callKeep;
> 
> ...
> 
>   @override
>   void callStateChanged(Call call, CallState callState) {
>     logger.d(callState.state);
>     // TODO Check outbound calls from DialpadScreen()
>     //if (callState.state == CallStateEnum.CALL_INITIATION) {
>     this._call = call;
>     this._callState = callState;
>     //}
>   }
> 
> ...
> 
>   void _callKeepCallBacks() {
>     _callKeep.on(CallKeepPerformAnswerCallAction(), answerCall);
>     _callKeep.on(CallKeepDidPerformDTMFAction(), didPerformDTMFAction);
>     _callKeep.on(
>         CallKeepDidReceiveStartCallAction(), didReceiveStartCallAction);
>     _callKeep.on(CallKeepDidToggleHoldAction(), didToggleHoldCallAction);
>     _callKeep.on(
>         CallKeepDidPerformSetMutedCallAction(), didPerformSetMutedCallAction);
>     _callKeep.on(CallKeepPerformEndCallAction(), endCall);
>   }
> 
>   Future<void> answerCall(CallKeepPerformAnswerCallAction event) async {
>     final String callUUID = event.callUUID;
>     logger.d('[answerCall] $callUUID');
>     _callKeep.setCurrentCallActive(callUUID);
>     _call.answer(helper.buildCallOptions());
>   }
> ```

How do you then listen to the CallKeep events because they are not firing off

**Comment by kirtiios** [comment]
Hello @georgenhari @ghenry 
how you integrated callkeep and sip-ua library together 
can you share some code  call connection related 
thank you in advance

**Comment by piyushkb** [comment]
> Hello @georgenhari @ghenry how you integrated callkeep and sip-ua library together can you share some code call connection related thank you in advance

bro any solution?

**Comment by kirtiios** [comment]
> > Hello @georgenhari @ghenry how you integrated callkeep and sip-ua library together can you share some code call connection related thank you in advance
> 
> bro any solution?

No,bro...i stopped this  task

**Comment by md-riaz** [comment]
Looking for the same solution....
