### ISSUE TITLE
IOS How to show incoming call only app is in background?

### ISSUE THREAD

**Issue by xyzbilal** [flutter-webrtc/callkeep#54]
Hi, I m trying to implement an softphone app works with janus gateway an webrtc. everything works fine. to keep app receive calls from janus I have to leave session alive all the time and when a call received my backend will send voip notification. 

the problem is backend cant know the app is alive or not and it should send notification everytime call received. my concern is  when my app is running I only show incoming call screen and if app is background I want to show callkit screen. 
I tried to add lifecycle of flutter WidgetsBindingObserver to control events but it didnt work properly. 
I use example app of this package for testing. 
 any idea will be appriciated. 

thanks.

**Comment by rekonvald** [comment]
Hi there! Should there be additional settings for IOS? I can't make it run there, app crashes on display incoming call

**Comment by ahmedJD** [comment]
the app crashes on display icoming call after destroying the app in ios

**Comment by ahmedJD** [comment]
@rekonvald the app crash when it's killed after display incomming call is there any solution?

**Comment by rekonvald** [comment]
I don't use this plugin any more

**Comment by ejimenez93** [comment]
@rekonvald -- what plugin are you using instead? We're having similar issues with this library when our app is terminated or in the background

**Comment by subhangiP** [comment]
@rekonvald 

> -- what plugin are you using instead? We're having similar issues with this library when our app is terminated or in the background

Have you found any solutions for both iOS and android?

**Comment by xyzbilal** [comment]
I finally recreated apps with native android java and ios  swift with native api's  provided. I learnt so much from this package. thanks.
