### ISSUE TITLE
Calling displayIncomingCall crashes app on IOS

### ISSUE THREAD

**Issue by rekonvald** [flutter-webrtc/callkeep#60]
Hi!

I am using FCM to process background messages and I want to call 

```
_callKeep.displayIncomingCall(callUUID, number,
        handleType: 'number', hasVideo: false);
```
as was mentioned into example. But this example was for Android, will it work for IOS? Or what setting should be done to make it work?

**Comment by xyzbilal** [comment]
You can test your ios notification with an app named push notification tester mentioned in this medium article 

`https://medium.com/mobile-appetite/how-to-test-your-push-notifications-implementation-on-ios-7138122fb3fb`

**Comment by rekonvald** [comment]
Thank you!

But I am getting FCM push notifications, and when I call displayIncomingCall application just crashes
