### ISSUE TITLE
Null safety

### ISSUE THREAD

**Issue by ghenry** [flutter-webrtc/callkeep#75]
Was just looking at this as I'm migrating my own code. Anyone started?

https://dart.dev/null-safety/migration-guide#migration-tool

Thanks.

**Comment by VadimBliz** [comment]
You can try my fork of this plugin, I already migrate this plugin to null safety.
https://github.com/VadimBliz/callkeep

**Comment by ghenry** [comment]
Pull request?

**Comment by cloudwebrtc** [comment]
Fixed https://github.com/flutter-webrtc/callkeep/commit/726db974788f1b66d856f03dfca03525c26b606a
